INSERT INTO webproducts.catalog (product_name, category, size, color, price, quantity_in_stock, date_added) VALUES ('T-Shirt', 'Clothing', 'M', 'Red', 19.99, 100, '2025-04-08');
INSERT INTO webproducts.catalog (product_name, category, size, color, price, quantity_in_stock, date_added) VALUES ('Jeans', 'Clothing', 'L', 'Blue', 49.99, 50, '2025-04-08');
INSERT INTO webproducts.catalog (product_name, category, size, color, price, quantity_in_stock, date_added) VALUES ('Jacket', 'Outerwear', 'M', 'Black', 89.99, 30, '2025-04-08');
INSERT INTO webproducts.catalog (product_name, category, size, color, price, quantity_in_stock, date_added) VALUES ('Sneakers', 'Footwear', '8', 'White', 59.99, 200, '2025-04-08');
INSERT INTO webproducts.catalog (product_name, category, size, color, price, quantity_in_stock, date_added) VALUES ('Sweater', 'Clothing', 'L', 'Grey', 29.99, 75, '2025-04-08');
INSERT INTO webproducts.catalog (product_name, category, size, color, price, quantity_in_stock, date_added) VALUES ('Dress', 'Clothing', 'S', 'Black', 59.99, 20, '2025-04-08');
INSERT INTO webproducts.catalog (product_name, category, size, color, price, quantity_in_stock, date_added) VALUES ('Hoodie', 'Clothing', 'M', 'Navy', 39.99, 150, '2025-04-08');
INSERT INTO webproducts.catalog (product_name, category, size, color, price, quantity_in_stock, date_added) VALUES ('Shorts', 'Clothing', 'L', 'Khaki', 25.99, 80, '2025-04-08');
INSERT INTO webproducts.catalog (product_name, category, size, color, price, quantity_in_stock, date_added) VALUES ('Scarf', 'Accessories', 'One Size', 'Red', 15.99, 200, '2025-04-08');
INSERT INTO webproducts.catalog (product_name, category, size, color, price, quantity_in_stock, date_added) VALUES ('Gloves', 'Accessories', 'One Size', 'Black', 9.99, 150, '2025-04-08');
INSERT INTO webproducts.catalog (product_name, category, size, color, price, quantity_in_stock, date_added) VALUES ('Boots', 'Footwear', '9', 'Brown', 89.99, 40, '2025-04-08');
INSERT INTO webproducts.catalog (product_name, category, size, color, price, quantity_in_stock, date_added) VALUES ('T-Shirt', 'Clothing', 'S', 'Green', 17.99, 120, '2025-04-08');
INSERT INTO webproducts.catalog (product_name, category, size, color, price, quantity_in_stock, date_added) VALUES ('Leggings', 'Clothing', 'M', 'Black', 29.99, 130, '2025-04-08');
INSERT INTO webproducts.catalog (product_name, category, size, color, price, quantity_in_stock, date_added) VALUES ('Cap', 'Accessories', 'One Size', 'Blue', 19.99, 90, '2025-04-08');
INSERT INTO webproducts.catalog (product_name, category, size, color, price, quantity_in_stock, date_added) VALUES ('Socks', 'Accessories', 'One Size', 'White', 5.99, 500, '2025-04-08');
INSERT INTO webproducts.catalog (product_name, category, size, color, price, quantity_in_stock, date_added) VALUES ('Blouse', 'Clothing', 'M', 'White', 39.99, 70, '2025-04-08');
INSERT INTO webproducts.catalog (product_name, category, size, color, price, quantity_in_stock, date_added) VALUES ('Skirt', 'Clothing', 'S', 'Pink', 24.99, 60, '2025-04-08');
INSERT INTO webproducts.catalog (product_name, category, size, color, price, quantity_in_stock, date_added) VALUES ('Sweater', 'Clothing', 'XL', 'Beige', 35.99, 50, '2025-04-08');
INSERT INTO webproducts.catalog (product_name, category, size, color, price, quantity_in_stock, date_added) VALUES ('Raincoat', 'Outerwear', 'L', 'Yellow', 69.99, 30, '2025-04-08');
INSERT INTO webproducts.catalog (product_name, category, size, color, price, quantity_in_stock, date_added) VALUES ('Polo', 'Clothing', 'M', 'Red', 22.99, 200, '2025-04-08');
INSERT INTO webproducts.catalog (product_name, category, size, color, price, quantity_in_stock, date_added) VALUES ('Cargo Pants', 'Clothing', 'L', 'Olive', 34.99, 80, '2025-04-08');
INSERT INTO webproducts.catalog (product_name, category, size, color, price, quantity_in_stock, date_added) VALUES ('Blazer', 'Clothing', 'L', 'Black', 89.99, 40, '2025-04-08');
INSERT INTO webproducts.catalog (product_name, category, size, color, price, quantity_in_stock, date_added) VALUES ('Chinos', 'Clothing', 'M', 'Navy', 45.99, 90, '2025-04-08');
INSERT INTO webproducts.catalog (product_name, category, size, color, price, quantity_in_stock, date_added) VALUES ('Boots', 'Footwear', '10', 'Black', 79.99, 60, '2025-04-08');
INSERT INTO webproducts.catalog (product_name, category, size, color, price, quantity_in_stock, date_added) VALUES ('Sneakers', 'Footwear', '7', 'Grey', 69.99, 100, '2025-04-08');
INSERT INTO webproducts.catalog (product_name, category, size, color, price, quantity_in_stock, date_added) VALUES ('Shirt', 'Clothing', 'S', 'Blue', 27.99, 75, '2025-04-08');
INSERT INTO webproducts.catalog (product_name, category, size, color, price, quantity_in_stock, date_added) VALUES ('Puffer Jacket', 'Outerwear', 'M', 'Red', 99.99, 25, '2025-04-08');
INSERT INTO webproducts.catalog (product_name, category, size, color, price, quantity_in_stock, date_added) VALUES ('Tank Top', 'Clothing', 'S', 'White', 14.99, 150, '2025-04-08');
INSERT INTO webproducts.catalog (product_name, category, size, color, price, quantity_in_stock, date_added) VALUES ('Joggers', 'Clothing', 'M', 'Black', 39.99, 120, '2025-04-08');
INSERT INTO webproducts.catalog (product_name, category, size, color, price, quantity_in_stock, date_added) VALUES ('Tracksuit', 'Clothing', 'L', 'Black', 59.99, 60, '2025-04-08');
INSERT INTO webproducts.catalog (product_name, category, size, color, price, quantity_in_stock, date_added) VALUES ('Fleece Jacket', 'Outerwear', 'XL', 'Grey', 79.99, 35, '2025-04-08');